version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 setup.py install

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install pytest pytest-cov mock flake8 codecov
            make flake8
            make test
            codecov
